### ISSUE TITLE
Can't install PAM for ubuntu touch

### ISSUE THREAD

**Issue by mutse** [UbuntuOpenStore/pamauthentication#1]
It can't find PAM libpam0g-dev:armhf for ubuntu touch when I compile this code, how to do it?
Thanks!

**Comment by bhdouglass** [comment]
How are you compiling the code?

**Comment by mutse** [comment]
I compile the code with qtcreator and lxd, and can't find libpam0g-dev:armhf package.

**Comment by bhdouglass** [comment]
Ok, so you should just be able to install the libpam0g-dev:armhf package in your lxd container and recompile.

**Comment by mutse** [comment]
Thanks!

**Comment by bhdouglass** [comment]
You're welcome!
